// Внутриигровые цены, целые Минетки. Не рыночные котировки.
export const catalog = [
  {
    id: "p250",
    weapon: "P250",
    name: "Песчаная буря",
    price: 100,
    color: "#6899ef",
    kind: "pistol",
  },
  {
    id: "glock",
    weapon: "Glock-18",
    name: "Лунная ночь",
    price: 250,
    color: "#9270f7",
    kind: "pistol",
  },
  {
    id: "mp9",
    weapon: "MP9",
    name: "Закат",
    price: 400,
    color: "#bc77ff",
    kind: "rifle",
  },
  {
    id: "m4",
    weapon: "M4A1-S",
    name: "Неоновый поток",
    price: 750,
    color: "#f16ec4",
    kind: "rifle",
  },
  {
    id: "ak",
    weapon: "AK-47",
    name: "Огненный след",
    price: 1500,
    color: "#ff7658",
    kind: "rifle",
  },
  {
    id: "awp",
    weapon: "AWP",
    name: "Северное сияние",
    price: 3000,
    color: "#59d6cb",
    kind: "sniper",
  },
  {
    id: "knife",
    weapon: "★ Керамбит",
    name: "Градиент",
    price: 7000,
    color: "#f4bf63",
    kind: "knife",
  },
  {
    id: "butterfly",
    weapon: "★ Нож-бабочка",
    name: "Тигриный клык",
    price: 15000,
    color: "#ffb04f",
    kind: "knife",
  },
];
export const findSkin = (id) => catalog.find((skin) => skin.id === id);
